// Tema migrado 1:1 del tailwind.config inline que se pasaba al CDN
// (Layout.astro). Cargado por Tailwind v4 vía `@config` en global.css.
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,tsx,ts,jsx,js,html}"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#fecaca",
        "error-container": "#3a0000",
        "on-primary-fixed": "#001a1f",
        "inverse-on-surface": "#0f0f17",
        "on-primary-container": "#cffafe",
        "tertiary-fixed-dim": "#d8b4fe",
        "surface-dim": "#0a0a0f",
        "primary-fixed-dim": "#22d3ee",
        "on-background": "#e4e4f0",
        "on-tertiary-container": "#ede9fe",
        "surface-container": "#12121a",
        "surface-container-high": "#1a1a24",
        "surface-variant": "#1f1f2b",
        "secondary-fixed-dim": "#c084fc",
        "surface-container-low": "#0f0f17",
        "secondary-fixed": "#e9d5ff",
        "on-surface": "#e4e4f0",
        "outline-variant": "#2a2a3a",
        "secondary-container": "#581c87",
        "inverse-surface": "#e4e4f0",
        "on-tertiary": "#0a0a0f",
        "primary-fixed": "#cffafe",
        "on-secondary": "#0a0a0f",
        "surface-tint": "#22d3ee",
        "surface-bright": "#22222f",
        outline: "#4c4c60",
        "surface-container-lowest": "#08080c",
        tertiary: "#c084fc",
        background: "#0a0a0f",
        "inverse-primary": "#0891b2",
        "tertiary-container": "#6b21a8",
        error: "#ff5370",
        "on-error": "#0a0a0f",
        "primary-container": "#0e7490",
        secondary: "#a855f7",
        "on-primary": "#0a0a0f",
        primary: "#22d3ee",
        "surface-container-highest": "#26263a",
        surface: "#0a0a0f",
        "on-surface-variant": "#9ca3af",
      },
      borderRadius: {
        none: "0px",
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["JetBrains Mono", "monospace"],
        body: ["JetBrains Mono", "monospace"],
        label: ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
};
