variables:
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"
  NPM_CONFIG_PREFER_OFFLINE: "true"

default:
  interruptible: true
  before_script:
    - node --version
    - npm --version

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
  policy: pull-push

stages:
  - install
  - validate
  - build
  - build_and_push_cr
  - deploy

include:
  - local: '/.ci-jobs.yml'
  - local: '/.cd-jobs.yml'